# Generated by Django 2.2.3 on 2019-07-26 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('displayName', models.CharField(max_length=2048)),
                ('locationType', models.CharField(max_length=64)),
                ('nameInLocalLanguage', models.BooleanField(default=False)),
                ('englishName', models.CharField(blank=True, max_length=256, null=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('crawlIP', models.CharField(blank=True, max_length=256, null=True)),
                ('stateShortCode', models.CharField(blank=True, max_length=2, null=True)),
                ('stateCode', models.CharField(blank=True, max_length=2, null=True)),
                ('districtCode', models.CharField(blank=True, max_length=4, null=True)),
                ('blockCode', models.CharField(blank=True, max_length=7, null=True)),
                ('panchayatCode', models.CharField(blank=True, max_length=10, null=True)),
                ('filepath', models.CharField(blank=True, max_length=2048, null=True)),
                ('isNIC', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('parentLocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.Location')),
            ],
            options={
                'db_table': 'location',
            },
        ),
    ]
