# Generated by Django 2.2.3 on 2019-07-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='blockName',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='districtName',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='panchayatName',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='stateName',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
