# Generated by Django 2.2.3 on 2019-07-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0002_auto_20190727_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='nicURL',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
