# Generated by Django 2.2.3 on 2019-07-28 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0003_location_nicurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportType', models.CharField(max_length=256)),
                ('reportURL', models.URLField(blank=True, max_length=2048, null=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('finyear', models.CharField(blank=True, max_length=2, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Location')),
            ],
            options={
                'db_table': 'report',
                'unique_together': {('location', 'reportType', 'finyear')},
            },
        ),
    ]
