# Generated by Django 2.2.3 on 2019-07-31 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0005_auto_20190728_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='inQueue', max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Report')),
            ],
            options={
                'db_table': 'crawlQueue',
            },
        ),
    ]
