# Generated by Django 2.2.3 on 2019-08-06 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0006_crawlqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlqueue',
            name='code',
            field=models.CharField(default=33, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crawlqueue',
            name='finyear',
            field=models.CharField(default=18, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crawlqueue',
            name='reportType',
            field=models.CharField(default='jobcardRegister', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crawlqueue',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.Report'),
        ),
    ]
