# Generated by Django 2.2.3 on 2019-08-06 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0007_auto_20190806_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawlqueue',
            old_name='code',
            new_name='locationCode',
        ),
    ]
