# Generated by Django 2.2.3 on 2019-08-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0008_auto_20190806_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlqueue',
            name='finyear',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
