# Generated by Django 2.2.3 on 2019-08-07 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0009_auto_20190806_0108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrawlQueue',
            new_name='TaskQueue',
        ),
        migrations.AlterModelTable(
            name='taskqueue',
            table='taskQueue',
        ),
    ]
