# Generated by Django 2.2.3 on 2019-08-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0010_auto_20190807_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskqueue',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskqueue',
            name='isError',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskqueue',
            name='response',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
