# Generated by Django 2.2.3 on 2019-08-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0011_auto_20190818_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('isAdult', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
