# Generated by Django 2.2.3 on 2019-08-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0012_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='finyear',
            field=models.CharField(blank=True, default='', max_length=2),
            preserve_default=False,
        ),
    ]
