# Generated by Django 2.2.3 on 2019-08-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0013_auto_20190819_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='nregaNICErrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errorType', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nregaNICError',
            },
        ),
    ]
