# Generated by Django 2.2.3 on 2019-08-25 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0014_nreganicerrors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nregaNICErrors',
            new_name='NREGANICError',
        ),
    ]
