# Generated by Django 2.2.3 on 2019-09-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0015_auto_20190825_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='excelURL',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
