"""
Core Models
"""
import time
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, \
                                        PermissionsMixin
from django.core.mail import EmailMultiAlternatives
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.loader import render_to_string
from django.urls import reverse
from django.conf import settings

from django.core.mail import EmailMultiAlternatives
from django.dispatch import receiver
from django.template.loader import render_to_string
from django.urls import reverse

from django_rest_passwordreset.signals import reset_password_token_created

# Create your models here.

def avatar_upload_path(instance, filename):
    """This function will return the upload path for avatar"""
    return '/'.join(["avatar",str(instance.id),filename])
class UserManager(BaseUserManager):
    """
    Custom User Manager Class
    """
    def create_user(self, email, password=None, **extra_fields):
        """Create and Saves user"""
        if not email:
            email = str(time.time())+"@libtech.in"
          #  raise ValueError("Users must have an email address")
            
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password):
        """Creates and saves new super user"""
        user = self.create_user(email, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    """custom user model that supports using email instead of username"""
    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255, null=True, unique=True)
    phone = models.CharField(max_length=255, null=True, unique=True)
    user_role = models.CharField(max_length=20, blank=True, null=True,
                                 default="student")
    is_active = models.BooleanField(default=True)
    autogenerated_email = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    login_attempt_count = models.PositiveSmallIntegerField(default=0)
    is_locked = models.BooleanField(default=False)
    otp_counter = models.PositiveIntegerField(default=0)
    otp_expiration = models.DateTimeField(null=True, blank=True)
    avatar = models.ImageField(blank=True, null=True,
                               upload_to=avatar_upload_path)
    avatar_url = models.URLField(max_length=1024, null=True, blank=True)
    provider = models.CharField(max_length=32, default="native")
    objects = UserManager()
    USERNAME_FIELD = 'email'

class OTP(models.Model):
    """This is the class for OTP"""
    phone = models.CharField(max_length=256, unique=True)
    otp_counter = models.PositiveIntegerField(default=0)
    otp_expiration = models.DateTimeField(null=True, blank=True)
    is_used = models.BooleanField(default=False)
    class Meta:
        """To define meta data attributes"""
        db_table = 'otp'
    def __str__(self):
        """Default str method for the class"""
        return f"{self.phone}"


@receiver(reset_password_token_created)
def password_reset_token_created(sender, instance, reset_password_token, *args, **kwargs):
    """
    Handles password reset tokens
    When a token is created, an e-mail needs to be sent to the user
    :param sender: View Class that sent the signal
    :param instance: View Instance that sent the signal
    :param reset_password_token: Token Model Object
    :param args:
    :param kwargs:
    :return:
    """
    # send an e-mail to the user
    context = {
        'current_user': reset_password_token.user,
        'username': reset_password_token.user.username,
        'email': reset_password_token.user.email,
        #'reset_password_url': "{}?token={}".format(reverse('user:password_reset:reset-password-request'), reset_password_token.key)
        'reset_password_url': "{}?token={}".format(settings.FRONTEND_PWDRESETCONFIRM_URL, reset_password_token.key)
    }

    # render email text
    email_html_message = render_to_string('email/user_reset_password.html', context)
    email_plaintext_message = render_to_string('email/user_reset_password.txt', context)

    msg = EmailMultiAlternatives(
        # title:
        "Password Reset for {title}".format(title="Some website title"),
        # message:
        email_plaintext_message,
        # from:
        "noreply@somehost.local",
        # to:
        [reset_password_token.user.email]
    )
    msg.attach_alternative(email_html_message, "text/html")
    msg.send()
