# Generated by Django 3.1 on 2020-08-22 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibtechTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'libtechtag',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('scheme', models.CharField(default='nrega', max_length=64)),
                ('location_type', models.CharField(max_length=64)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('nic_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('display_name', models.CharField(max_length=2048)),
                ('name_not_english', models.BooleanField(default=False)),
                ('english_name', models.CharField(blank=True, max_length=256, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('crawl_ip', models.CharField(blank=True, max_length=256, null=True)),
                ('state_short_code', models.CharField(blank=True, max_length=2, null=True)),
                ('state_code', models.CharField(blank=True, max_length=2, null=True)),
                ('state_name', models.CharField(blank=True, max_length=256, null=True)),
                ('district_code', models.CharField(blank=True, max_length=4, null=True)),
                ('district_name', models.CharField(blank=True, max_length=256, null=True)),
                ('block_code', models.CharField(blank=True, max_length=7, null=True)),
                ('block_name', models.CharField(blank=True, max_length=256, null=True)),
                ('panchayat_code', models.CharField(blank=True, max_length=10, null=True)),
                ('panchayat_name', models.CharField(blank=True, max_length=256, null=True)),
                ('s3_filepath', models.CharField(blank=True, max_length=2048, null=True)),
                ('is_nic', models.BooleanField(default=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_crawl_date', models.DateTimeField(blank=True, null=True)),
                ('is_data_available', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('libtech_tag', models.ManyToManyField(to='nrega.LibtechTag')),
                ('parent_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.location')),
            ],
            options={
                'db_table': 'location',
            },
        ),
    ]
