# Generated by Django 3.1 on 2020-08-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='libtech_tag',
            field=models.ManyToManyField(blank=True, null=True, to='nrega.LibtechTag'),
        ),
    ]
