# Generated by Django 3.0.2 on 2020-01-06 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=256)),
                ('report_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('excel_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('finyear', models.CharField(blank=True, default='NA', max_length=2, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Location')),
            ],
            options={
                'db_table': 'report',
                'unique_together': {('location', 'report_type', 'finyear')},
            },
        ),
    ]
