# Generated by Django 3.0.2 on 2020-01-06 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0002_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='crawlIP',
            new_name='crawl_ip',
        ),
    ]
