# Generated by Django 3.1 on 2020-08-23 00:02

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0003_auto_20200823_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('location_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('report_type', models.CharField(db_index=True, max_length=256)),
                ('archive_reports', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('report_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('excel_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('finyear', models.CharField(blank=True, default='NA', max_length=2, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('libtech_tag', models.ManyToManyField(blank=True, db_index=True, to='nrega.LibtechTag')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.location')),
            ],
            options={
                'db_table': 'report',
                'unique_together': {('location', 'report_type', 'finyear')},
            },
        ),
    ]
