# Generated by Django 3.1 on 2020-08-23 11:10

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0004_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='archive_reports',
            field=django_mysql.models.JSONField(blank=True, default=list, null=True),
        ),
    ]
