# Generated by Django 3.0.2 on 2020-01-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0004_auto_20200110_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibtechTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'libtechtag',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='libtech_tag',
            field=models.ManyToManyField(to='nrega.LibtechTag'),
        ),
    ]
