# Generated by Django 3.1 on 2020-08-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0005_auto_20200823_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location_name',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
    ]
