# Generated by Django 3.0.2 on 2020-03-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0006_taskqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskqueue',
            name='location_class',
            field=models.CharField(default='NREGAPanchayat', max_length=64),
        ),
    ]
