# Generated by Django 3.1 on 2020-08-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0006_report_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=256)),
                ('location_code', models.CharField(max_length=20)),
                ('location_class', models.CharField(default='NREGAPanchayat', max_length=64)),
                ('scheme', models.CharField(default='nrega', max_length=64)),
                ('start_finyear', models.CharField(blank=True, max_length=2, null=True)),
                ('end_finyear', models.CharField(blank=True, max_length=2, null=True)),
                ('status', models.CharField(default='inQueue', max_length=256)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('report_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('force_download', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('response', models.CharField(blank=True, max_length=256, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('process_name', models.CharField(blank=True, max_length=256, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'taskQueue',
            },
        ),
    ]
