# Generated by Django 3.1 on 2020-09-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0008_report_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
