# Generated by Django 3.0.7 on 2020-07-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0009_location_data_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskqueue',
            name='force_download',
            field=models.BooleanField(default=False),
        ),
    ]
