# Generated by Django 3.1 on 2020-10-17 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nrega', '0009_report_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='zipped bundle', max_length=2048)),
                ('report_types', models.CharField(max_length=2048)),
                ('finyears', models.CharField(blank=True, max_length=2048, null=True)),
                ('location_code', models.CharField(blank=True, max_length=20, null=True)),
                ('location_type', models.CharField(blank=True, max_length=20, null=True)),
                ('libtech_tags', models.CharField(blank=True, max_length=2048, null=True)),
                ('report_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bundle',
            },
        ),
    ]
