# Generated by Django 3.1 on 2020-10-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0010_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='is_bundle_created',
            field=models.BooleanField(default=False),
        ),
    ]
