# Generated by Django 3.1 on 2020-10-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0011_bundle_is_bundle_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='report_format',
            field=models.CharField(blank=True, default='csv', max_length=20, null=True),
        ),
    ]
