# Generated by Django 3.1 on 2020-10-17 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0012_bundle_report_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundle',
            old_name='report_url',
            new_name='bundle_url',
        ),
    ]
