# Generated by Django 3.1 on 2020-10-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0013_auto_20201017_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='filename',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
