# Generated by Django 3.1 on 2020-10-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0014_bundle_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskqueue',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
