# Generated by Django 3.1 on 2020-10-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0015_taskqueue_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='filename',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
