# Generated by Django 3.1 on 2020-11-25 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0016_auto_20201018_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskqueue',
            name='task_type',
            field=models.CharField(default='download', max_length=64),
        ),
        migrations.CreateModel(
            name='CrawlSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='zipped bundle', max_length=2048)),
                ('report_type', models.CharField(max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.libtechtag')),
            ],
            options={
                'db_table': 'crawlschedule',
            },
        ),
    ]
