# Generated by Django 3.1 on 2021-01-30 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0018_bundle_is_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finyear', models.CharField(default='NA', max_length=2)),
                ('record_no', models.CharField(default='NA', max_length=256)),
                ('record_type', models.CharField(default='NA', max_length=256)),
                ('location_type', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('location_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('last_download_date', models.DateField(blank=True, null=True)),
                ('is_recurring_download', models.BooleanField(default=True)),
                ('threshold_days', models.PositiveSmallIntegerField(default=14)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('libtech_tag', models.ManyToManyField(blank=True, db_index=True, to='nrega.LibtechTag')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.location')),
            ],
            options={
                'db_table': 'record',
                'unique_together': {('location', 'record_no', 'finyear')},
            },
        ),
    ]
