# Generated by Django 3.1 on 2021-01-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0019_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_no',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
