# Generated by Django 3.1 on 2021-01-31 04:57

from django.db import migrations, models
import nrega.models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0020_auto_20210131_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='additional_fields',
            field=models.JSONField(default=nrega.models.get_default_additional_fields),
        ),
        migrations.AlterField(
            model_name='report',
            name='archive_reports',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
