# Generated by Django 3.1 on 2021-01-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0021_auto_20210131_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='finyear',
            field=models.CharField(db_index=True, default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_no',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
